- msg/MotionPlanRequest.msg
This is a change related to https://github.com/ros-planning/moveit_ros/pull/547 and adds a motion_execution_time_factor scaling factor for optionally slowing down trajectories.
> Add time factor to MotionPlanRequest

- CMakeLists.txt
- msg/PlannerParams.msg
- srv/GetPlannerParams.srv
- srv/SetPlannerParams.srv
Added message type and services to get/set planner parameters through move_group interface.
This replaces PR #15 that was made against indigo-devel.
> messages and services to get/set planner params

- msg/MotionPlanRequest.msg
This is a change related to ros-planning/moveit_ros#634 and adds a maximum acceleration scaling factor for optionally limiting trajectory acceleration.
> Adding acceleration scaling factor

- CMakeLists.txt
- srv/ApplyPlanningScene.srv
This service takes a PlanningScene message and applies it to the monitored
scene.
See https://groups.google.com/forum/#!topic/moveit-users/D7MWZEUSKLc
for a discussion on why this makes sense to add.
Ideally it should include a `bool success` field, but it is not possible to
apply the scene and check for success without ABI changes, so leave it out for
now to get this change pushed to indigo.
With kinetic we might want to think about adding a `bool success` field here
and make ```newPlanningSceneMessage``` return ```bool``` instead of ```void```.
> add new srv ApplyPlanningScene

- CHANGELOG.rst
- package.xml
Addressing suggestion at https://github.com/ros-planning/moveit_msgs/commit/c5c4c6181e3e9a24ac1f8020e1ad3dbd05e13b00#commitcomment-18705574
> Update maintainers. Bad encoding.

- srv/ExecuteKnownTrajectory.srv
Not entirely sure if this suggestion is the right move, but looking at places like [this comment](https://github.com/ros-planning/moveit/pull/60/files/e094ddc3a5bd5237d0c52f1356a186cb9203d5ea#r75147036) we want to switch to the new action.
> Add note in ExecuteKnownTrajectory service to recommend ExecuteTrajectory action.

- .travis.yml
- README.md
> Switch travis to moveit_ci

- CMakeLists.txt
- srv/GraspPlanning.srv
Until now the move group pick action uses the grasp planning service from manipulation_msgs.
However, this doesn't use moveit_msgs::Grasp which has evolved since then.
The new service in moveit_msgs uses its own Grasp.msg and overall aims to replace the old functionality
using moveit types.
> new GraspPlanning service to replace manipulation_msgs version

- action/Pickup.action
- action/Place.action
Add new fields to store planning time of the pick-and-place capability.
`MoveGroup.action` already has this.
> Add fields to store planning time in pick-and-place

- srv/GetPlanningScene.srv
The get_planning_scene service should return the full scene if no specific component is specified. PR in main repository still pending.
Discussed in:
https://github.com/ros-planning/moveit/pull/1424
> Add comment all scene components returned if no components specified

- action/Place.action
- msg/CollisionObject.msg
Some field descriptions in Place.action were phrased wrong, or still referred to grasping/pick up instead of placing.
> Correct typos/better phrasing in Place.action

- msg/DisplayRobotState.msg
This PR is WIP because I haven't implemented the necessary changes in the MoveIt Rviz Plugin for displaying a robot state, but I don't think it would be hard. 
This is a useful feature because I've used a workaround for it for years, but the workaround [causes issues](https://github.com/ros-planning/panda_moveit_config/issues/33). The workaround, used in MoveIt Visual Tools [here](https://github.com/ros-planning/panda_moveit_config/issues/33), is to move the robot to a very far away location in Rviz, such that its invisible. 
With this new flag, we could remove the need for a virtual_joint that moves the robot, and instead just set a bool.
If there are no issues with this feature, I will eventually implement the rest of the change. Or ask someone else to hopefully implement it for me.
> Ability to hide visualized robot states

- CMakeLists.txt
- msg/CartesianPoint.msg
- msg/CartesianTrajectory.msg
- msg/CartesianTrajectoryPoint.msg
- msg/GenericTrajectory.msg
- msg/MotionPlanRequest.msg
Related to https://github.com/ros-planning/moveit/issues/804
Everything is up for debate.
My points so far:
* I used the `JointOrCartesianTrajectory` to avoid confusion regarding the contents of the message. Ideally `trajectory_msgs` could host this message.
* I chose `geometry_msgs/TransformStamped` to describe the points of a Cartesian trajectory to allow for any base frame to be used to define any point. This allows for multiple seeds even for different end effector(s) although leaves some questions regarding the properness of this arbitrary point. 
* Something like [this](https://github.com/bmagyar/industrial_moveit/blob/cartesian-seed/stomp_moveit/src/stomp_planner.cpp#L577) could be added to a conversion library to ease moving from-to the different spaces using the IK solver …
> Add seed trajectories to MotionPlanRequest

- CMakeLists.txt
This PR intends to suppress Wredundant-decls warnings.
> Suppress Wredundant-decls warnings

- CMakeLists.txt
- srv/ChangeDriftDimensions.srv
- srv/ChangeFreeDimensions.srv
Very similar to PR #61 
#61 defines a service to set velocities in certain dimensions to 0.
This PR defines a service to allow the robot to drift in a smooth but unregulated way (in the specified dimensions). In preparation to take advantage of task redundancy.
> Change jogging drift dimensions

- msg/PlaceLocation.msg
Similar to the field grasp_quality in the Grasp message, this can give users a possibility to prioritize place locations, e.g. because they are more stable or more likely to succeed.
I am looking forward to hear your opinions. Has anybody else ever been in a situation where this would have been useful?
> Add field quality to PlaceLocation

- msg/CollisionObject.msg
This (partially) reverts commit 6350bfb3db0bd8da35020ed4ddcf74bc93170c95.
We keep the improvements in the comments.
> Revert "Allow subframes in CollisionObjects (#50)"

- CMakeLists.txt
- action/MoveGroupSequence.action
- msg/MotionSequenceItem.msg
- msg/MotionSequenceRequest.msg
- msg/MotionSequenceResponse.msg
- srv/GetMotionSequence.srv
Backport in anticipation of the release as discussed here: https://github.com/ros-planning/moveit_msgs/issues/71#issuecomment-626514604.  @v4hn please review.
This is a prerequisite for the Pilz Motion Planner.
This should just be rebased to cherry-pick the original commit onto melodic-devel.
> [melodic-devel] Add messages to plan for sequences (#65)

- CHANGELOG.rst
- package.xml
I did run the prerelease tests with level 0 & 1, is level 0 sufficient for future releases (level 1 took more than 3 hours for moveit_msgs!) .?
git tag must be pushed manually once this PR gets merged.
> [melodic] Update version info to 0.10.1

- msg/PositionIKRequest.msg
I removed `attempts` field from `PositionIKRequest.msg` because `attemts` field is not used now.
I think this field may be confusing.
Please refer to:
https://github.com/ros-planning/moveit/pull/1288
> remove attempts field from PositionIKRequest.msg

- msg/MotionPlanRequest.msg
See ros-planning/moveit#1790 for more details.
These additional fields are needed to pass these values from the `move_group_interface` to a planning adapter, that recomputes the time parameterization of the trajectory to match the given Cartesian speed.
> add fields to set cartesian end effector speed

- msg/OrientationConstraint.msg
As explained and discussed in #89
>I think it could be useful to add an extra field to the message for orientation constraints that specifies how the orientation should be parameterized when testing the constraints. Currently, the tolerances are applied to the XYZ Euler angles (intrinsic rotations), but they could be just as well be applied to any three number parameterization.
> While working on #2092, I seem to notice that exponential coordinates (rotation angle * rotation axis) performed better for projection-based sampling.
>[...], but for planners that don't like Euler angles, it is useful to have this alternative. For example, TrajOpt does not use Euler angles.
I'm [almost finished](https://github.com/JeroenDM/moveit/tree/orientation-constraints-parameterization) with a …
> Add parameterization type to orientation constraints

- CHANGELOG.rst
- package.xml
These changelog changes were generated using `catkin_generate_changelogs` and then I deleted some lines from it that I found just extra noise.
This is in preparation of releasing the moveit repo itself on Noetic.
> 0.11.2 (Noetic)

- action/Pickup.action
- action/Place.action
Address issue ros-planning/moveit/issues/2667
> Remove erroneous comment from Pickup/Place action files

- .github/workflows/prerelease.yaml
@henningkayser If you merge this one first then the workflow dispatch thing will start to work because then it will have a pre-release github action with a workflow_dispatch in the default branch.
> pre-release test for noetic

- .github/workflows/prerelease.yaml
I pushed this into the repo so we can run it on this branch to test if it works before merging.
It looks like industrial_ci supports pre-release testing for ros2: https://github.com/ros-industrial/industrial_ci/blob/master/industrial_ci/src/tests/ros_prerelease.sh#L25
> pre-release testing workflow for ros2

- srv/GetCartesianPath.srv
See [ros_planning/moveit#2674](https://github.com/ros-planning/moveit/pull/2674) for more details.
These additional fields are needed to pass these values from the move_group_interface to a planning adapter, that recomputes the time parameterization of the trajectory to match the given Cartesian speed for the function `computeCartesianPath`
> Added message fields for setting the maximum cartesian end effector for cartesian paths

- msg/DisplayTrajectory.msg
> fix long comments in msg

- msg/CollisionObject.msg
With https://github.com/ros-planning/moveit/pull/2037 merged, this disclaimer can be removed.
> Remove disclaimer from CollisionObject pose

- .github/workflows/industrial_ci_action.yml
Our ccache is broken in CI, thus our ccache action should be updated to match Github's new ccache action v2 as per https://github.com/ros-planning/moveit2/pull/619
> [ros2] Fix ccache

- .github/workflows/industrial_ci_action.yml
Our ccache is broken in CI, thus our ccache action should be updated to match Github's new ccache action v2 as per https://github.com/ros-planning/moveit2/pull/619
> [master] Fix ccache

- msg/JointLimits.msg
Since MoveIt is starting to get the capability to handle jerk limits in some contexts, I think we should add a jerk limits field here.
MoveIt uses this message a lot internally, including [here](https://github.com/ros-planning/moveit2/blob/4d13e2e3636175916bb98fc89224c2521e3b6004/moveit_ros/planning/robot_model_loader/src/robot_model_loader.cpp#L125) in robot_model_loader.
> Add jerk to JointLimits.msg

- action/Place.action
- dox/definePlanningRequest.dox
- msg/AllowedCollisionMatrix.msg
- msg/AttachedCollisionObject.msg
- msg/ConstraintEvalResult.msg
- msg/ContactInformation.msg
- msg/Grasp.msg
- msg/MotionPlanDetailedResponse.msg
- msg/PlaceLocation.msg
- msg/PlanningOptions.msg
- msg/PlanningScene.msg
- msg/PlanningSceneComponents.msg
- msg/PositionConstraint.msg
- msg/PositionIKRequest.msg
- msg/VisibilityConstraint.msg
- msg/WorkspaceParameters.msg
- srv/ExecuteKnownTrajectory.srv
- srv/GetPositionFK.srv
- srv/GetPositionIK.srv
As the title says... My editor shows trailing whitespace in red :)
> clean all trailing whitespace in definitions

- msg/MotionPlanRequest.msg
- srv/GetCartesianPath.srv
Renamed the cartesian end effector field to cartesian link field because any link speed can be limited by this message if needed
This cleans up and replaces #122
> Rename Cartesian end effector field to Cartesian link

- CONTRIBUTING.md
- LICENSE
What the title says, this is basically a copy of what I did against the ros2 and master branch.  This has been prompted by comments on rosdistro PRs for releases asking for these files.  I'd like to standardize on using ament_copyright to generate them so they are uniform and in ros2 we can enable that test everywhere.
This command was used to generate these:
```
ament_copyright --add-missing "Willow Garage, Inc." bsd_3clause
```
> Unify license file notice [melodic-devel]

- msg/OrientationConstraint.msg
... per this issue: https://github.com/ros-planning/moveit2/issues/1586
Merge with this moveit2 PR:  https://github.com/ros-planning/moveit2/pull/1592
> Factor of 2 in OMPL orientation constraints, to match kinematic_constraints

- msg/MotionPlanRequest.msg
- srv/GetCartesianPath.srv
Partly fixes https://github.com/ros-planning/moveit2/issues/1967
This PR adds `max_velocity_scaling_factor` and `max_acceleration_scaling_factor` fields to the `GetCartesianPath` srv request so that downstream interfaces can appropriately scale cartesian trajectories derived from cartesian interpolations.
> Add fields in GetCartesianPath srv to scale velocity and acceleration

- action/ExecuteTrajectory.action
Add the ability to specify list of controller names to use for execution. 
Required for https://github.com/ros-planning/moveit2/pull/2257
> Add controller names to ExecuteTrajectory action

- CMakeLists.txt
- msg/MotionPlanRequest.msg
- msg/PipelineState.msg
To improve debugging of the planning pipeline https://github.com/ros-planning/moveit2/pull/2429 adds a publisher that publishes intermediate results of the planning pipeline stages. This PR adds the message type that is used
> Add PipelineState message

- msg/MoveItErrorCodes.msg
When planning with MoveIt and MTC, we often assign the FAILURE error code. This is in an effort to add more description on why planning/execution failed.
> Add error message string to MoveItErrorCode msg
