- CMakeLists.txt
- srv/CheckIfRobotStateExistsInWarehouse.srv
- srv/DeleteRobotStateFromWarehouse.srv
- srv/GetRobotStateFromWarehouse.srv
- srv/ListRobotStatesInWarehouse.srv
- srv/RenameRobotStateInWarehouse.srv
- srv/SaveRobotStateToWarehouse.srv
Added service definitions for Warehouse robot-state access. Required for changes made in https://github.com/ros-planning/moveit_ros/pull/594
> F#276 add db state

- msg/MotionPlanRequest.msg
Once #19 gets merged I'll rebase to include that change from there.
> Adding acceleration scaling factor (Cherry-pick #17 into jade)

- CMakeLists.txt
- action/ExecutePath.action
For ros-planning/moveit_ros#719
Being moved from #24
> Add .action file for execution trajectory in a ROS action

- package.xml
Thanks to @davetcoleman for pointing it out:
https://github.com/ros-planning/moveit_msgs/pull/26#discussion_r75628563
> fix broken maintainer tags

- .travis.yml
- README.md
> Improve Travis and README

- .travis.yml
- README.md
> Remove jade test from kinetic branch

- .travis.yml
> Remove kinetic test from Travis branch

- .travis.yml
- CMakeLists.txt
- package.xml
Modernize `package.xml` and fix `catkin_lint` issues.
> fix catkin_lint issues

- CMakeLists.txt
- srv/ChangeControlDimensions.srv
See [moveit PR 1724](https://github.com/ros-planning/moveit/pull/1724) for more info
> Added service file for moveit_experimental/moveit_jog_arm

- CMakeLists.txt
- srv/UpdatePointcloudOctomap.srv
Corresponding PR: https://github.com/ros-planning/moveit/pull/1984
> Add service to update pointcloud octomap

- msg/CollisionObject.msg
This is part of a PR implementing https://github.com/ros-planning/moveit/issues/2025.
> Add origin Pose to CollisionObject

- CMakeLists.txt
- srv/ChangeControlDimensions.srv
- srv/ChangeDriftDimensions.srv
Backporting these PRs to melodic-devel for jog arm:
* https://github.com/ros-planning/moveit_msgs/pull/68
* https://github.com/ros-planning/moveit_msgs/pull/63
@AndyZe please review and let me know if this is all that will be needed to before we can add jog arm to melodic_devel in moveit.
> [melodic-devel] Jog arm backport

- srv/GetCartesianPath.srv
Cleanup and refined wording of the original pull-request
Please review and merge @rhaschke .
Supersedes #44 .
> add {prismatic,revolute}_jump_threshold

- msg/CollisionObject.msg
https://github.com/ros-planning/moveit_msgs/pull/69#issuecomment-689591627 definitely is correct about this.
Hopefully we can remove this soon enough again.
> add a disclaimer to CO about pose not working yet

- CHANGELOG.rst
One small change, this next release should be really easy.
> Changelogs for Noetic release 0.11.1

- CHANGELOG.rst
- msg/CollisionObject.msg
- msg/OrientationConstraint.msg
- package.xml
Preparing for Debian release:
* master branch sync
* updating changelog, version bump
> Changelogs and version bump for Foxy

- msg/MotionPlanRequest.msg
- msg/PlannerInterfaceDescription.msg
- srv/GetPlannerParams.srv
- srv/SetPlannerParams.srv
Required for https://github.com/ros-planning/moveit/pull/2127
> Support specifying pipeline ids with planning requests

- .github/workflows/industrial_ci_action.yml
This fixes ccache (using a directory that works) and adds uploading failed test results.
> Fix ccache in CI [ros2]

- .github/workflows/industrial_ci_action.yml
Same as https://github.com/ros-planning/moveit_msgs/pull/102 but for master branch.
> Fix ccache in CI [master]

- .github/workflows/industrial_ci_action.yml
Same as https://github.com/ros-planning/moveit_msgs/pull/102 but for melodic-devel branch.
> Fix ccache on CI [melodic-devel]

- LICENSE.txt
> Add BSD License to repository

- CONTRIBUTING.md
- LICENSE
> Add License Notice

- action/Pickup.action
- action/Place.action
- msg/MotionPlanRequest.msg
- msg/PlannerInterfaceDescription.msg
- package.xml
- srv/GetPlannerParams.srv
- srv/SetPlannerParams.srv
Up to https://github.com/ros-planning/moveit_msgs/tree/460caab755cfe018ad07effd7dd808127a7e5c61
> Sync with master branch

- CHANGELOG.rst
- package.xml
New release for Foxy, Galactic, Rolling. Minor version bump since this includes the master sync.
> [ROS 2] Release 2.1.0

- CHANGELOG.rst
- package.xml
This is to release the latest changes into galactic and rolling.
Please use the rebase option on this.
> 2.2.0 release for G/R

- msg/OrientationConstraint.msg
> Note on +/- constraint tolerances

- .github/workflows/format.yml
https://github.com/ros-planning/moveit2/issues/1736
> Fix clang-format-14 version in Format CI job
